apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Removed for multicluster subscriptions operator
#- amq-operator-subscription.yaml
#- amq-broker.yaml
- messaging-configmap.yaml
- messaging-deployment.yaml
- messaging-svc.yaml
