apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# MCS disregards namespaces but keep it in here
namespace: manuela-sensors-mcs

resources:
- machine-sensor-namespace.yaml


bases:
- ../../../templates/manuela-openshift/machine-sensor

patchesStrategicMerge:
- machine-sensor-1-deployment.yaml
- machine-sensor-2-deployment.yaml

configMapGenerator:
- name: machine-sensor-1
  behavior: merge
  env: machine-sensor-1-configmap.properties

- name: machine-sensor-2
  behavior: merge
  env: machine-sensor-2-configmap.properties


images:
- name: machine-sensor
  newName: quay.io/manuela/iot-software-sensor
  newTag: quickstart

